### ISSUE TITLE
Arbitrage contract error

### ISSUE THREAD

**Issue by donalddominko** [Robsonsjre/FlashloanUsecases#10]
Hi, I need a little help with arbitrage contract I keep getting this error when I try to call "makeArbitrage":

status | false Transaction mined but execution failed
-- | --
transaction hash | 0x89483cebae54a2943700ef10ce531f9bc6e50f661b4304f57d328e0dd794421b
from | 0xf783c77b3282E86DF0Eda02972281E0768F5df31
to | Arbitrage.makeArbitrage(uint256) 0x7a8f0c81bA8e6CcF06Ea95D108f4E9c3aD32Ef56
gas | 3000000 gas
transaction cost | 321070 gas
hash | 0x89483cebae54a2943700ef10ce531f9bc6e50f661b4304f57d328e0dd794421b
input | 0x3dd...00000
decoded input | { 	"uint256 amount": { 		"_hex": "0x056bc75e2d63100000" 	} }
decoded output | -
logs | []
value | 0 wei

**Comment by Robsonsjre** [comment]
Could you try it again? The pools are unbalanced again!

If dont work, try to invert orders of UNISWAP_FACTORY_A and B

**Comment by Robsonsjre** [comment]
Im closing this issue for now, fell free to telll if you runed into another problem.
