### ISSUE TITLE
Where can I see the 1B Dai of the flashloan ?

### ISSUE THREAD

**Issue by cocoper89** [Robsonsjre/FlashloanUsecases#11]
![image](https://user-images.githubusercontent.com/66026089/86131644-93a0e780-baee-11ea-8efd-6530a11b5c79.jpeg)
![Uploading 86131662...]()

**Comment by Robsonsjre** [comment]
What you mean with your question, sorry?

**Comment by cocoper89** [comment]
Did the flash loAn was successful?
And if yes ... where is the (test dai ) profit ?

Sent from my iPhone

On Jun 30, 2020, at 11:58 PM, Rob <notifications@github.com> wrote:

﻿

What you mean with your question, sorry?

**Comment by cocoper89** [comment]
The code is the same to do the arbitrage flash loan not in the kovan network ?
I would like the code  if posible

Sent from my iPhone

On Jul 1, 2020, at 5:11 AM, Coco Guillen <cocoguillen89@hotmail.com> wrote:

﻿ Did the flash loAn was successful?
And if yes ... where is the (test dai ) profit ?

Sent from my iPhone

On Jun 30, 2020, at 11:58 PM, Rob <notifications@github.com> wrote:

﻿

What you mean with your question, sorry?

**Comment by amadeobrands** [comment]
The Question is a bit unclear please explain what you need?

**Comment by amadeobrands** [comment]
Closing this issue.
Please send me DM on forum or reopen issue if there is something.
