### ISSUE TITLE
How to do this in the mainnet ?

### ISSUE THREAD

**Issue by OscarJensen** [Robsonsjre/FlashloanUsecases#13]
I understand that this applies to the Kovan network. Now how to build a flashloan in the MainNetwork using this code?

**Comment by Robsonsjre** [comment]
You just need to change the network into remix to mainnet, and change contract addresses. You can find the other addresses here:
https://docs.aave.com/developers/deployed-contracts/deployed-contract-instances

**Comment by OscarJensen** [comment]
Thank you !
