### ISSUE TITLE
Problem deploying it to Mainnet

### ISSUE THREAD

**Issue by OscarJensen** [Robsonsjre/FlashloanUsecases#14]
Hi, so i want to deploy my code using the mainnet. 
I put in the right adresses. Now i understand I need to choose : "Web3 provider" right? (not the injected web3) 
Im using a mac and how do I enable this code? geth --rpc --rpccorsdomain https://remix.ethereum.org
where do i type it in, basically How do I get this started correctly? :)
 

all the best!

**Comment by Robsonsjre** [comment]
You can choose the injected one, but instead of Kovan, you need to select Mainnet!

**Comment by OscarJensen** [comment]
ok ok!

**Comment by OscarJensen** [comment]
Yeah it shows me that Gas failure sign... damn why is this so expensive
