### ISSUE TITLE
Mainnetwork problem

### ISSUE THREAD

**Issue by OscarJensen** [Robsonsjre/FlashloanUsecases#15]
Hey so...this pops up and I cannot deploy my contract...whats the matter?
What i did:
got 25$ worth of DAI in my metamask and 0.4 eth
1.copy + paste the code from git hub
2. added the right addresses...please check for me is :
UNISWAP 1 factory this? : 0xc0a47dFe034B400B47bDaD5FecDa2621de6c4d95
UNISWAP 2 factory this? : 0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f
3. then added the token addresses 
saved it deployed and this comes up... what to do and what does this mean? 

![Zrzut ekranu 2020-07-10 o 17 39 20](https://user-images.githubusercontent.com/66013564/87172348-674a4f80-c2d4-11ea-8f04-b68a558a13e9.png)

**Comment by OscarJensen** [comment]
Hello?

**Comment by Robsonsjre** [comment]
I see on the top left that you are connected to the mainnet, and in our example we did t Kovan network. Are you really trying to deploy it to mainnet, otherwise you should practice on Kovan first!

**Comment by OscarJensen** [comment]
Yes i am trying to perform a flash loan on the mainnet. I practiced in the Kovan but when i try to deploy it to the mainnet this thing pops up that the gas estimation failed...does that mean i need more eth in my wallet? What is the answer?

**Comment by Robsonsjre** [comment]
In mainnet you should do the arbitrage in a different pool exchange. Kyber or Curve for example...You can not just deploy that contract and change the addresses. In mainnet Uniswap v2 have a different architecture. This example is just to capture the logic of an Arbitrageur contractt, but you will need to create your own! If you need help, I can help you with Uniswap v2

**Comment by OscarJensen** [comment]
Hey thanks for your reply! Yes, It would be great. Could you tell me about
the mainnet's uniswapV2 architecture and what to do exactly if i want to do
an arbitrage in uniswap? im really devoted to this.

czw., 13 sie 2020 o 17:13 Rob <notifications@github.com> napisał(a):

**Comment by CryptoEatsTheWorld** [comment]
> 
> 
> In mainnet you should do the arbitrage in a different pool exchange. Kyber or Curve for example...You can not just deploy that contract and change the addresses. In mainnet Uniswap v2 have a different architecture. This example is just to capture the logic of an Arbitrageur contractt, but you will need to create your own! If you need help, I can help you with Uniswap v2

I'd love help with a live mainnet example/template too for uniswap.

Also, I am getting the same gas error message when I try to run the kovan example you gave on the kovan network.  I don't know what is wrong.

**Comment by OscarJensen** [comment]
The code I showed you there is with uniswap pools from the mainnet...
I just want to know how do I build a smart contract in a form of a flash
loan that I actually can deploy. I thought I could just change the
addresses to mainnet addresses and it would work...

>
