### ISSUE TITLE
Lost Contract

### ISSUE THREAD

**Issue by OkkerBotes** [Robsonsjre/FlashloanUsecases#19]
Today and thank you for a course with brilliant content.

I would like to know how I can access an already deployed contract.  After deploying the contract and transferring funds to it run successfully. I  then closed the remix window.  How would I communicate with the contract again?  I have copied the address that I sent the funds to from my metamask history and pasted that into the at address field in the run and deploy section of  remix. But alas doesn't resolve the deployed contract. 

In this case, it's not the end of the world since this is just a test net but if this was a real world I would have certainly wanted to be able to access my contract again.

**Comment by OkkerBotes** [comment]
Anny pointers on this?

**Comment by amadeobrands** [comment]
You need the TX Hash of the contract then load it back in.
