### ISSUE TITLE
makeArbitrage() call fails 1000000000000000000

### ISSUE THREAD

**Issue by CatalystJesal** [Robsonsjre/FlashloanUsecases#22]
![image](https://user-images.githubusercontent.com/47870568/108129558-4a65ce00-70a6-11eb-9f4f-09c2be229400.png)

I even sent test DAI to the contract before calling the makeArbitrage function, but it didn't work.

**Comment by JohnChangUK** [comment]
Getting this error too, can anyone address this?

**Comment by Robsonsjre** [comment]
Probably you are trying to get a loan bigger than the amount available on Aave's pool
