### ISSUE TITLE
Bag Gateway & No AAve Faucet

### ISSUE THREAD

**Issue by ghost** [Robsonsjre/FlashloanUsecases#24]
Hey,

1) https://faucet.kovan.network/  gives Bad Gateway now. ive requested on glitter but still waiting. Can you please send me Kovan Test ETH to

0x53CD3F17F2723bA185e67989A73a5aAFb5fAca2f

2) the aave things has been resolved. stil need the KETH please,

thank you

**Comment by Robsonsjre** [comment]
Sent
https://kovan.etherscan.io/tx/0xf715651c5d7ceddab784cc0f65c6a862d555deb791e82d8fbafa68245c4d7033
