### ISSUE TITLE
Failed transaction on Etherscan - applicable for Post byzantium blocks only

### ISSUE THREAD

**Issue by Dante9988** [Robsonsjre/FlashloanUsecases#25]
My steps:
Send 3000 DAI to the contract
Executed the contract

Actual result: When executed contract, Remix shows "Gas Estimation Error" and if proceed with and sumbit the transaction, on etherescan im getting Falied transaction and TX was reverted

<img width="1678" alt="Screen Shot 2021-06-23 at 5 46 19 PM" src="https://user-images.githubusercontent.com/47313096/123178965-f735ca80-d44d-11eb-86e8-8e8c25ba9530.png">
<img width="1792" alt="Screen Shot 2021-06-23 at 5 47 20 PM" src="https://user-images.githubusercontent.com/47313096/123178967-f866f780-d44d-11eb-8e2d-fc8beaa1c9c6.png">

NOTE: I believe this is not a fee issue, it is related to ethereum hard fork (byzantium blocks), but still I dont quite understand why its failing

**Comment by Robsonsjre** [comment]
Have you tried smaller amounts? Sometimes the transaction fails because AAVE pool doesn't have enough funds to lend

**Comment by Dante9988** [comment]
I resolved the issue, it was a compiler issue that had different versions, so i will close out the issue
