### ISSUE TITLE
Error and warning when compiling 'myfirstflashloan.sol'

### ISSUE THREAD

**Issue by Jason247365** [Robsonsjre/FlashloanUsecases#29]
Hi, when I try to compile the code I get the below...

https://github.com/mrdavey/ez-flashloan/blob/remix/contracts/aave/FlashLoanReceiverBase.sol:33:13: Warning: Return value of low-level calls not used.
_destination.call.value(_amount)("");
^----------------------------------^

and

https://github.com/mrdavey/ez-flashloan/blob/remix/contracts/aave/FlashLoanReceiverBase.sol:33:13: Warning: Return value of low-level calls not used.
_destination.call.value(_amount)("");
^----------------------------------^

Can you please give some advice how to proceed?

Thank

**Comment by Robsonsjre** [comment]
Usually there is no problem since is just a Warning, and not an Error.

**Comment by Jason247365** [comment]
Thanks Rob, sorry that was my fault.

Is it possible for you to send me some KETH?...my request on Gitter only got fulfilled by 0.001 KETH so is not enough for me to play around.

Thanks in advance.

0x307a6EFD55eae2f4a2498C92703849d81235E70E

**Comment by Robsonsjre** [comment]
Done

**Comment by Jason247365** [comment]
Cheers boss.
