### ISSUE TITLE
can i get some assistance?

### ISSUE THREAD

**Issue by nastyatimosha** [Robsonsjre/FlashloanUsecases#7]
hello.. i am new at the academy of Ivan.. but so far i found everything very confusing.. maybe because i am not a programmer and i am not really interested in code and programming..  I AM A TRADER... for the last 10 years i was trading all types of instruments.. so of course i got interested when i saw Ivan speaking on his videos about arbitrage.. 

So the thing is that you prepared all this stuff of DEFI 201 and arbitrage, more in a "programmer way" and you forgot about traders... but in fact.. if you think about it.. arbitrage is a trading concept and not a programming concept.. so you should made the course dedicated to traders! because really.. i have already spent many hours trying to get this working and i just cannot..

For couple seconds i ask you to stand on the shoes of a trader who never in his life wrote a line of code and who doesnt understand most of the terms that you are mentioning in the course.. and you know? any trader who comes to your courses looking for the arbitrage.. when he starts to listen all those terms and to see the coding and that.. he will just run away.. same as i wanted just to close the browser and go to my charts to continue doing my work as usually

So please guys.. as Amadeo said in every of his videos.. if we have a request, we could submit it here.. then my request and i guess, talking from all traders interested on this... PLEASE, make a little document, slide, video or whatever.. specifying each steps, one by one, to do this of arbitrage.... but do it for traders.. not for programmers..

this means that for example.. is not necessary that you try to explain all the terms, functions and that.. would be easier if you just make a little document like...
 
Step 1. Get metamask wallet
Step 2. Go to Remix Ethereum
Step 3. copy and paste your wallet address in this exact line of code.. 
Step 4..... 

in fact, all the videos that you made, you could resume it a little document with each step.. and then any TRADER could get into this without complications...

I hope you can do this and post it here or in the DEFI 201 files.. otherwise i really think that hardly any trader will be even interested on it

**Comment by nastyatimosha** [comment]
ohh by the way.. if this courses and everything about the flash loans arbitrage is possible to be done ONLY by experienced programmers.. then please put a note in the academy and in your courses... also would be nice that Ivan say this notification in his videos.. then people and traders will not waste their time accessing to this things

**Comment by amadeobrands** [comment]
Thank you for your feedback :) 
There is also a course focused on trading in the Acedemy this DeFi 201 is also for traders and there is an explanation of how to do arbitrage with an easy drag and drop GUI ... The last section shows an basic Flash Loan and how to program it. It shows the basics and it is up to you if you want to dive deeper into the technical or the trading side of it.

If you completed the other courses recommended before doing this course let me know if you still get stock and where happy to help out.

**Comment by Thaddeus19** [comment]
At the beginning of the course Amadeo indicates the courses as prerequisites
DeFi 101
Ethereum Smart Contract Programming 101
Blockchain & Bitcoin 101
Algorithmic Trading & Technical Analysis

I think your experience as a trader will help you a lot to identify trading opportunities and you could lean on platforms like https://furucombo.app/ to execute the flahsloan

**Comment by nastyatimosha** [comment]
> Thank you for your feedback :)
> There is also a course focused on trading in the Acedemy this DeFi 201 is also for traders and there is an explanation of how to do arbitrage with an easy drag and drop GUI ... The last section shows an basic Flash Loan and how to program it. It shows the basics and it is up to you if you want to dive deeper into the technical or the trading side of it.
> 
> If you completed the other courses recommended before doing this course let me know if you still get stock and where happy to help out.

Amdeo, thanks for answer... and sorry but i must disagree.. as i wrote in my first message, i am trader, not programmer... and even that i follow and every day watch Ivan's videos, and i listen every day his advertisings of Academy... i was NEVER interested on it.. why? because i am trader.. not programmer.. actually is not only me, we are a little group of traders.. and we never been interested at all in the code, technology and fundamentals of crypto or blockchain.. we only care about the PRICE of the assets and the profit i can make with it... so when Ivan said about the course of FLASH LOANS ARBITRAGE... for very first time i got interested and i subscribed and i paid the membership.. i agreed to pay a crazy fee of $1500 for the membership.. and you know why?? because Ivan said that WE DONT NEED TO HAVE ANY PREVIOUS KNOWLEDGE... HE MENTION IN THE VIDEOS THAT EVEN IF WE DONT KNOW WHAT IS A CONTRACT OR THE MOST BASIC CONCEPTS.. DOESNT MATTER WE CAN TAKE THE COURSE AND YOU WILL GUIDE US STEP BY STEP... 

you verify this statements in his last video couple days ago.. https://www.youtube.com/watch?v=Rhm2AY8mhIY&t=4s

but now.. after i paid the memebership.. i cannot find any support.. any help.. you roughly answer once a week.. so to be honest.. if you are not able to provide us with a simple for TRADERS guide of how to get done the arbitrage.. then please i request you to refund my money.. i repeat once again.. i just signed in because of the FLASH LOANS ARBITRAGE.. i paid the cost.. and i want to get a simple code where i could just replace wallets, coin pairs.. and excecute the arbitrage.... i am not interested in Defi 101, i am not interested in ETH fundamentals.. i am not interested actually in Defi fundamentals..... i am on Defi and crypto only because it provides me PROFIT!!! 

some little details... The code you posted here is completely different than the code of your videos in the Defi201... this is not fair, because this is very very confusing for people.. you should not do this.. you should post here the exact coin and the exact procedure that the brazilian guy did in the video!!!

**Comment by nastyatimosha** [comment]
> Thank you for your feedback :)
> There is also a course focused on trading in the Acedemy this DeFi 201 is also for traders and there is an explanation of how to do arbitrage with an easy drag and drop GUI ... The last section shows an basic Flash Loan and how to program it. It shows the basics and it is up to you if you want to dive deeper into the technical or the trading side of it.
> 
> If you completed the other courses recommended before doing this course let me know if you still get stock and where happy to help out.

I forgot to say.. the fact that you send us to use a GUI makes your courses Defi 201 worthless and meaningless... for what we paid $1500 if you will end sending us to use another thing????????? dont even know what is a GUI and i dont know what companies or services provide that.. and not any of the traders in my group knows this also.. if we would knew it then we would not be interested in your courses from the beginning..

**Comment by nastyatimosha** [comment]
> At the beginning of the course Amadeo indicates the courses as prerequisites
> DeFi 101
> Ethereum Smart Contract Programming 101
> Blockchain & Bitcoin 101
> Algorithmic Trading & Technical Analysis
> 
> I think your experience as a trader will help you a lot to identify trading opportunities and you could lean on platforms like https://furucombo.app/ to execute the flahsloa

sorry.. i must disagree.. i paste the answer that i sent here to Amadeo to you also take reference..

Amdeo, thanks for answer... and sorry but i must disagree.. as i wrote in my first message, i am trader, not programmer... and even that i follow and every day watch Ivan's videos, and i listen every day his advertisings of Academy... i was NEVER interested on it.. why? because i am trader.. not programmer.. actually is not only me, we are a little group of traders.. and we never been interested at all in the code, technology and fundamentals of crypto or blockchain.. we only care about the PRICE of the assets and the profit i can make with it... so when Ivan said about the course of FLASH LOANS ARBITRAGE... for very first time i got interested and i subscribed and i paid the membership.. i agreed to pay a crazy fee of $1500 for the membership.. and you know why?? because Ivan said that WE DONT NEED TO HAVE ANY PREVIOUS KNOWLEDGE... HE MENTION IN THE VIDEOS THAT EVEN IF WE DONT KNOW WHAT IS A CONTRACT OR THE MOST BASIC CONCEPTS.. DOESNT MATTER WE CAN TAKE THE COURSE AND YOU WILL GUIDE US STEP BY STEP... 

you verify this statements in his last video couple days ago.. https://www.youtube.com/watch?v=Rhm2AY8mhIY&t=4s

but now.. after i paid the memebership.. i cannot find any support.. any help.. you roughly answer once a week.. so to be honest.. if you are not able to provide us with a simple for TRADERS guide of how to get done the arbitrage.. then please i request you to refund my money.. i repeat once again.. i just signed in because of the FLASH LOANS ARBITRAGE.. i paid the cost.. and i want to get a simple code where i could just replace wallets, coin pairs.. and excecute the arbitrage.... i am not interested in Defi 101, i am not interested in ETH fundamentals.. i am not interested actually in Defi fundamentals..... i am on Defi and crypto only because it provides me PROFIT!!! 

some little details... The code you posted here is completely different than the code of your videos in the Defi201... this is not fair, because this is very very confusing for people.. you should not do this.. you should post here the exact coin and the exact procedure that the brazilian guy did in the video!!!

**Comment by christiancarmona** [comment]
> > At the beginning of the course Amadeo indicates the courses as prerequisites
> > DeFi 101
> > Ethereum Smart Contract Programming 101
> > Blockchain & Bitcoin 101
> > Algorithmic Trading & Technical Analysis
> > I think your experience as a trader will help you a lot to identify trading opportunities and you could lean on platforms like https://furucombo.app/ to execute the flahsloa
> 
> sorry.. i must disagree.. i paste the answer that i sent here to Amadeo to you also take reference..
> 
> Amdeo, thanks for answer... and sorry but i must disagree.. as i wrote in my first message, i am trader, not programmer... and even that i follow and every day watch Ivan's videos, and i listen every day his advertisings of Academy... i was NEVER interested on it.. why? because i am trader.. not programmer.. actually is not only me, we are a little group of traders.. and we never been interested at all in the code, technology and fundamentals of crypto or blockchain.. we only care about the PRICE of the assets and the profit i can make with it... so when Ivan said about the course of FLASH LOANS ARBITRAGE... for very first time i got interested and i subscribed and i paid the membership.. i agreed to pay a crazy fee of $1500 for the membership.. and you know why?? because Ivan said that WE DONT NEED TO HAVE ANY PREVIOUS KNOWLEDGE... HE MENTION IN THE VIDEOS THAT EVEN IF WE DONT KNOW WHAT IS A CONTRACT OR THE MOST BASIC CONCEPTS.. DOESNT MATTER WE CAN TAKE THE COURSE AND YOU WILL GUIDE US STEP BY STEP...
> 
> you verify this statements in his last video couple days ago.. https://www.youtube.com/watch?v=Rhm2AY8mhIY&t=4s
> 
> but now.. after i paid the memebership.. i cannot find any support.. any help.. you roughly answer once a week.. so to be honest.. if you are not able to provide us with a simple for TRADERS guide of how to get done the arbitrage.. then please i request you to refund my money.. i repeat once again.. i just signed in because of the FLASH LOANS ARBITRAGE.. i paid the cost.. and i want to get a simple code where i could just replace wallets, coin pairs.. and excecute the arbitrage.... i am not interested in Defi 101, i am not interested in ETH fundamentals.. i am not interested actually in Defi fundamentals..... i am on Defi and crypto only because it provides me PROFIT!!!
> 
> some little details... The code you posted here is completely different than the code of your videos in the Defi201... this is not fair, because this is very very confusing for people.. you should not do this.. you should post here the exact coin and the exact procedure that the brazilian guy did in the video!!!

I'm also not a programmer. 
So far I've just taken the Defi 101 course from the academy and I almost finish the Defi 201 course. I did have a small issue with metamask and setting up the Gas Limit. (Seems I have a newer version of Metamask, and this new version has "hidden" this option in the "Advanced Options") but it only took me just 5 minutes to figure that out. After that I was able to perform the flashloan without any issues whatsoever.
I don't regret paying the fee for the academy, in fact I am willing to start the smart contract programming course as soon as I finish Defi 201. 

If you are looking for a ready to go tool where you only need to replace wallet and token, which you are only going to GET PROFIT from without learning anything or thinking a little bit, how much are you willing to pay for that tool? 
I can commit to quit my 9-5 job and focus on building you that tool so you won't need to do anything, put any effort nor learn or build anything. 
I'm willing to get paid for learning and building.

**Comment by nastyatimosha** [comment]
> > > At the beginning of the course Amadeo indicates the courses as prerequisites
> > > DeFi 101
> > > Ethereum Smart Contract Programming 101
> > > Blockchain & Bitcoin 101
> > > Algorithmic Trading & Technical Analysis
> > > I think your experience as a trader will help you a lot to identify trading opportunities and you could lean on platforms like https://furucombo.app/ to execute the flahsloa
> > 
> > 
> > sorry.. i must disagree.. i paste the answer that i sent here to Amadeo to you also take reference..
> > Amdeo, thanks for answer... and sorry but i must disagree.. as i wrote in my first message, i am trader, not programmer... and even that i follow and every day watch Ivan's videos, and i listen every day his advertisings of Academy... i was NEVER interested on it.. why? because i am trader.. not programmer.. actually is not only me, we are a little group of traders.. and we never been interested at all in the code, technology and fundamentals of crypto or blockchain.. we only care about the PRICE of the assets and the profit i can make with it... so when Ivan said about the course of FLASH LOANS ARBITRAGE... for very first time i got interested and i subscribed and i paid the membership.. i agreed to pay a crazy fee of $1500 for the membership.. and you know why?? because Ivan said that WE DONT NEED TO HAVE ANY PREVIOUS KNOWLEDGE... HE MENTION IN THE VIDEOS THAT EVEN IF WE DONT KNOW WHAT IS A CONTRACT OR THE MOST BASIC CONCEPTS.. DOESNT MATTER WE CAN TAKE THE COURSE AND YOU WILL GUIDE US STEP BY STEP...
> > you verify this statements in his last video couple days ago.. https://www.youtube.com/watch?v=Rhm2AY8mhIY&t=4s
> > but now.. after i paid the memebership.. i cannot find any support.. any help.. you roughly answer once a week.. so to be honest.. if you are not able to provide us with a simple for TRADERS guide of how to get done the arbitrage.. then please i request you to refund my money.. i repeat once again.. i just signed in because of the FLASH LOANS ARBITRAGE.. i paid the cost.. and i want to get a simple code where i could just replace wallets, coin pairs.. and excecute the arbitrage.... i am not interested in Defi 101, i am not interested in ETH fundamentals.. i am not interested actually in Defi fundamentals..... i am on Defi and crypto only because it provides me PROFIT!!!
> > some little details... The code you posted here is completely different than the code of your videos in the Defi201... this is not fair, because this is very very confusing for people.. you should not do this.. you should post here the exact coin and the exact procedure that the brazilian guy did in the video!!!
> 
> I'm also not a programmer.
> So far I've just taken the Defi 101 course from the academy and I almost finish the Defi 201 course. I did have a small issue with metamask and setting up the Gas Limit. (Seems I have a newer version of Metamask, and this new version has "hidden" this option in the "Advanced Options") but it only took me just 5 minutes to figure that out. After that I was able to perform the flashloan without any issues whatsoever.
> I don't regret paying the fee for the academy, in fact I am willing to start the smart contract programming course as soon as I finish Defi 201.
> 
> If you are looking for a ready to go tool where you only need to replace wallet and token, which you are only going to GET PROFIT from without learning anything or thinking a little bit, how much are you willing to pay for that tool?
> I can commit to quit my 9-5 job and focus on building you that tool so you won't need to do anything, put any effort nor learn or build anything.
> I'm willing to get paid for learning and building.

------------------------
i also executed the flash loans many times and for many amounts of tokens.. that is not the problem.. the problem is the arbitrage.. and for me, without the arbitrage.. the flash loan is worthless..
As you explained in your message.. you are not a programmer.. but you are interested on that.. and this is why you will continue the PROGRAMMING COURSE... but me, mya group and most of traders i know... are absolutely not interested in programming or anything that has to do with code... and the main point here is that arbitrage is a 100% purely trading concept.. the fact that is possible to do arbitrage with couple lines of code, doesnt means that a trader is interested in programming....

so yes.. i want a ready to go tool where i only replace wallets and tokens.. and this is what IVAN advertise in his videos.. he says in every video that we dont need to have any previous knowledge.. and as you can see.. this Amadeo and Ivan and nobody answer here for many days! nobody assist.. nobody help.. do you think this is worth to pay $1500???? the videos that you watch.. you can watch them for free online.. and even better videos..

anyway.. thanks for your offer to build me the tool.. but even that i am not a programmer, i understand that for the arbitrage is not even necessary a tool.. as you can see the code needed for the arbitrage is very short.. is not a big science.. but of course is necessary to have it correct and exact... but this guys here made a mess with the code.. so we are still waiting to they fix it

**Comment by Robsonsjre** [comment]
> > Hmmm...can you send me also the pic of your Remix screen?
> 
> thank you for your answers and support.. this is what we need...
> 
> i have couple questions and i would thank if you explain me...
> 
> 1. in the video, you make a profit of $11.. is that a real profit that you can withdraw? i mean.. any profit we make with the test net.. is possible to withdraw? or is just like a fake profit?
> 2. could you create an example of arbitrage in the mainnet? or this is only possible in the clones and test net?

@christiancarmona already gave good answers! 💯 
2. What you can do to test in mainnet, it's send some DAI  to your deployed contract to pay some fees (you will need 1 DAI to pay for ~1000 flash borrowed)

**Comment by Robsonsjre** [comment]
> Here you go
> http://prntscr.com/sxen58
> http://prntscr.com/sxenei

Apparently it's everything right. Can you try:
1) comment the line `require(daiBought > totalAmount)` and them
2) send 100 AaveDAI to your contract after deploying it (so the contract can have money to pay for the fees)
3) run makeArbitrage with 10 DAI
and them send the print of the etherscan transaction here! 

Sorry for the delay!

**Comment by christiancarmona** [comment]
It worked this time, @Robsonsjre 
but as I commented the line `require(daiBought > totalDebt, "Did not profit");` it didn't stop the transaction from being unprofitable. 
Here is the transaction. 
https://kovan.etherscan.io/tx/0x3e0011acba583861b158ecb74d30315dabaae25b9caa4dec79949f0311ec2059

Do I have the wallets in the correct order? I've been doing several tests and the amount of DAI is every time less and less 😅

I have another question, do I need to send DAI to the contract every time I run it? As I can see in the transaction, every time I run the transaction, the amount I deposited to the contract is sent back to my wallet minus the loss of the unprofitable transaction. 
Here you can find the contract and history of transactions:
https://kovan.etherscan.io/address/0x2f613c9f9fa56e710e31a6608b83496cce9e8327

**Comment by amadeobrands** [comment]
> It worked this time, @Robsonsjre
> but as I commented the line `require(daiBought > totalDebt, "Did not profit");` it didn't stop the transaction from being unprofitable.
> Here is the transaction.
> https://kovan.etherscan.io/tx/0x3e0011acba583861b158ecb74d30315dabaae25b9caa4dec79949f0311ec2059
> 
> Do I have the wallets in the correct order? I've been doing several tests and the amount of DAI is every time less and less 😅
> 
> I have another question, do I need to send DAI to the contract every time I run it? As I can see in the transaction, every time I run the transaction, the amount I deposited to the contract is sent back to my wallet minus the loss of the unprofitable transaction.
> Here you can find the contract and history of transactions:
> https://kovan.etherscan.io/address/0x2f613c9f9fa56e710e31a6608b83496cce9e8327

Flash Loans are much harder then you think.
But if you find a Flash Loan Arbitrage opportunity that can happen then you can make great profits.

On our Flash Loan Playground, we did create some arbitrage opportunities between DAI and BAT.
You can play around and train.

**Comment by amadeobrands** [comment]
@christiancarmona @nastyatimosha I will close this issue.
Discussions are best on the forum https://forum.ivanontech.com/t/lets-hack-flash-loans-flash-loan-assignment-discussion/16639
