### ISSUE TITLE
Problem with arbitrage flash loan between 4 tokens

### ISSUE THREAD

**Issue by Thaddeus19** [Robsonsjre/FlashloanUsecases#9]
Hi Amadeo
I need your help with a question, because if I try to do more than one swap between several tokens, it won't allow me. I put the token addresses but it only makes the switch between Dai and Bat. I attach the code. Thank you

pragma solidity ^0.5.0;

import "https://github.com/mrdavey/ez-flashloan/blob/remix/contracts/aave/FlashLoanReceiverBase.sol";
import "https://github.com/mrdavey/ez-flashloan/blob/remix/contracts/aave/ILendingPool.sol";
import "https://github.com/Robsonsjre/FlashloanUsecases/blob/master/contracts/interfaces/IUniswap.sol";

//1 DAI = 1000000000000000000 (18 decimals)
/*
 * Arbitrageur is a contract to simulate the usage of flashloans
 * to make profit out of a market inbalacement
 *
 * For this example we deployed 2 Uniswap instances which we'll
 * call by ExchangeA and ExchangeB
 *
 * The steps happens as following:
 * 1. Borrow DAI from Aave
 * 2. Buy BAT with DAI on ExchangeA
 * 3. Sell BAT for DAI on ExchangeB
 * 4. Buy MKR with DAI on ExchangeC
 * 3. Sell MKR for DAI on ExchangeD
 * 2. Buy SNX with DAI on ExchangeE
 * 3. Sell SNX for DAI on ExchangeF
 * 4. Repay Aave loan
 * 5. Keep the profits
 */
contract Arbitrageur is
    FlashLoanReceiverBase(address(0x506B0B2CF20FAA8f38a4E2B524EE43e1f4458Cc5)){ //primer paso declarar las direcciones de los contratos del token y de los exchange
	
	address public constant SNX_ADDRESS = 0x7FDb81B0b8a010dd4FFc57C3fecbf145BA8Bd947;
	address public constant MKR_ADDRESS = 0x61e4CAE3DA7FD189e52a4879C7B8067D7C2Cc0FA;
    address public constant DAI_ADDRESS = 0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD;
    address public constant BAT_ADDRESS = 0x2d12186Fbb9f9a8C28B3FfdD4c42920f8539D738;
    address public constant UNISWAP_FACTORY_A = 0xECc6C0542710a0EF07966D7d1B10fA38bbb86523;
    address public constant UNISWAP_FACTORY_B = 0x54Ac34e5cE84C501165674782582ADce2FDdc8F4;
	address public constant UNISWAP_FACTORY_C = 0xECc6C0542710a0EF07966D7d1B10fA38bbb86523;
    address public constant UNISWAP_FACTORY_D = 0x54Ac34e5cE84C501165674782582ADce2FDdc8F4;
	address public constant UNISWAP_FACTORY_E = 0x54Ac34e5cE84C501165674782582ADce2FDdc8F4;
	address public constant UNISWAP_FACTORY_F = 0xECc6C0542710a0EF07966D7d1B10fA38bbb86523;
	
    ILendingPool public lendingPool;
    IUniswapExchange public exchangeA;
    IUniswapExchange public exchangeB;
    IUniswapFactory public uniswapFactoryA;
    IUniswapFactory public uniswapFactoryB;
	IUniswapExchange public exchangeC;
    IUniswapExchange public exchangeD;
    IUniswapFactory public uniswapFactoryC;
    IUniswapFactory public uniswapFactoryD;
	IUniswapExchange public exchangeE;
    IUniswapExchange public exchangeF;
    IUniswapFactory public uniswapFactoryE;
    IUniswapFactory public uniswapFactoryF;
	
    constructor() public {
        // Instantiate Uniswap Factory A
        uniswapFactoryA = IUniswapFactory(UNISWAP_FACTORY_A);
        // get Exchange A Address
        address exchangeA_address = uniswapFactoryA.getExchange(DAI_ADDRESS);
        // Instantiate Exchange A
        exchangeA = IUniswapExchange(exchangeA_address);

        //Instantiate Uniswap Factory B
        uniswapFactoryB = IUniswapFactory(UNISWAP_FACTORY_B);
        // get Exchange B Address
        address exchangeB_address = uniswapFactoryB.getExchange(BAT_ADDRESS);
        //Instantiate Exchange B
        exchangeB = IUniswapExchange(exchangeB_address);
		
		   // Instantiate Uniswap Factory C
        uniswapFactoryC = IUniswapFactory(UNISWAP_FACTORY_C);
        // get Exchange C Address
        address exchangeC_address = uniswapFactoryC.getExchange(DAI_ADDRESS);
        // Instantiate Exchange C
        exchangeC = IUniswapExchange(exchangeC_address);

        //Instantiate Uniswap Factory D
        uniswapFactoryD = IUniswapFactory(UNISWAP_FACTORY_D);
        // get Exchange D Address
        address exchangeD_address = uniswapFactoryD.getExchange(MKR_ADDRESS);
        //Instantiate Exchange D
        exchangeD = IUniswapExchange(exchangeD_address);
		
		   // Instantiate Uniswap Factory E
        uniswapFactoryE = IUniswapFactory(UNISWAP_FACTORY_E);
        // get Exchange E Address
        address exchangeE_address = uniswapFactoryE.getExchange(DAI_ADDRESS);
        // Instantiate Exchange E
        exchangeA = IUniswapExchange(exchangeE_address);

        //Instantiate Uniswap Factory F
        uniswapFactoryF = IUniswapFactory(UNISWAP_FACTORY_F);
        // get Exchange F Address
        address exchangeF_address = uniswapFactoryF.getExchange(SNX_ADDRESS);
        //Instantiate Exchange F
        exchangeF = IUniswapExchange(exchangeF_address);
		
        // get lendingPoolAddress
        address lendingPoolAddress = addressesProvider.getLendingPool();
        //Instantiate Aaave Lending Pool B
        lendingPool = ILendingPool(lendingPoolAddress);
    }

	event loanProfit(uint256 revenue, uint256 totalDebt, uint256 dairevenue); //declaro el evento y las informacion que voy a enviar a traves de él

    /*
     * Start the arbitrage
     */
    function makeArbitrage(uint256 amount) public onlyOwner {
        bytes memory data = "";

        ERC20 dai = ERC20(DAI_ADDRESS);
        lendingPool.flashLoan(address(this), DAI_ADDRESS, amount, data);

        // Any left amount of DAI is considered profit
        uint256 profit = dai.balanceOf(address(this));
		
        // Sending back the profits
        require(
            dai.transfer(msg.sender, profit),
            "Could not transfer back the profit"
        );
    }

    function executeOperation(
        address _reserve,
        uint256 _amount,
        uint256 _fee,
        bytes calldata _params
    ) external {
        // If transactions are not mined until deadline the transaction is reverted
        uint256 deadline = getDeadline();

        ERC20 dai = ERC20(DAI_ADDRESS);
        ERC20 bat = ERC20(BAT_ADDRESS);
		ERC20 mkr = ERC20(MKR_ADDRESS);
		ERC20 snx = ERC20(SNX_ADDRESS);
		
		// Buying BAT at Exchange A
        require(
            dai.approve(address(exchangeA), _amount),
		    "Could not approve DAI sell"
        );

        uint256 tokenBought = exchangeA.tokenToTokenSwapInput(
            _amount,
			1,
            1,
            deadline,
            BAT_ADDRESS
        );

        require(
            bat.approve(address(exchangeB), tokenBought),
            "Could not approve DAI sell"
        );

        // Selling BAT at Exchange B
           uint256 daiBought = exchangeB.tokenToTokenSwapInput(
	        tokenBought,
            1,
            1,
            deadline,
            DAI_ADDRESS
        );
		
		// Buying MKR at Exchange C
        require(
            dai.approve(address(exchangeC), daiBought),
            "Could not approve DAI sell"
        );

        uint256 buymkr = exchangeC.tokenToTokenSwapInput(
            daiBought,
            1,
            1,
            deadline,
            MKR_ADDRESS
        );

        require(
            mkr.approve(address(exchangeD), buymkr),
            "Could not approve DAI sell"
        );

        // Selling MKR at Exchange D
          uint256 sellmkr = exchangeD.tokenToTokenSwapInput(
	        buymkr,
            1,
            1,
            deadline,
            DAI_ADDRESS
        );
		
			// Buying SNX at Exchange E
        require(
            dai.approve(address(exchangeE), sellmkr),
            "Could not approve DAI sell"
        );

        uint256 buysnx = exchangeE.tokenToTokenSwapInput(
            sellmkr,
            1,
            1,
            deadline,
            SNX_ADDRESS
        );

        require(
            snx.approve(address(exchangeF), buysnx),
            "Could not approve DAI sell"
        );

        // Selling SNX at Exchange F
          uint256 dairevenue = exchangeF.tokenToTokenSwapInput(
	        buysnx,
            1,
            1,
            deadline,
            DAI_ADDRESS
        );

        // Repay loan
        uint256 totalDebt = _amount.add(_fee);
	
			
		uint256 revenue = dairevenue - totalDebt;
		
		
        
		require(dairevenue > totalDebt, "Did not profit");
		
		
			
        transferFundsBackToPoolInternal(_reserve, totalDebt);
        
		
		//withdrawAll;
		
		emit loanProfit(revenue,  totalDebt,  dairevenue); //hago que el evento envie la informacion que necesitamos
		
    }

    function getDeadline() internal view returns (uint256) {
        return now + 3000;
    }
    
  
    
	function withdrawAll () public onlyOwner returns (uint){
	   ERC20 dai = ERC20(DAI_ADDRESS);

       uint256 gain = dai.balanceOf(address(this));
       uint toTransfer = gain;
       gain =0;
       msg.sender.transfer(toTransfer); //si esta accion falla hace un revert de la operacion
       return toTransfer;
       }

}

**Comment by amadeobrands** [comment]
Thanks for this.
WoW nice, swapping between 4 tokens I'm not sure if we tested the contracts for this.
We only made it so it would work with 2 tokens but it should work if you want to swap to other tokens in between.

I see that ERC20 snx is used this is not possible jet you first will have to add a factory contract for snx in order to do that. Also, it seems SNX and MKR are not correctly entered in the code it seems your just copied the code and forgot some parameters.

**Comment by Thaddeus19** [comment]
In the ConstantAddressesKovan.sol contract comes the following information
// ERC20 address
  address internal constant WETH_ADDRESS = 0xd0A1E359811322d97991E03f863a0C30C2cF029C;
  address internal constant MKR_ADDRESS = 0xAaF64BFCC32d0F15873a02163e7E500671a4ffcD;
  address internal constant AAVE_DAI_ADDRESS = 0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD;

  // DEX contracts
  address internal constant UNISWAP_FACTORY_A = 0x179F4Cb26F2dDdb23eE50568Cb66151E1C99bCe8;
  address internal constant UNISWAP_FACTORY_B = 0xCfbcBbA561417e714c48EAe2C25B4a59e05F74b7;
  address internal constant KYBER_ETH_ADDRESS = 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE;
  address internal constant KYBER_WRAPPER = 0x68c56FF0E7BBD30AF9Ad68225479449869fC1bA0;
  address internal constant UNISWAP_WRAPPER = 0x2A4ee140F05f1Ba9A07A020b07CCFB76CecE4b43;
  address internal constant ETH2DAI_WRAPPER = 0x823cde416973a19f98Bb9C96d97F4FE6C9A7238B;
  address internal constant OASIS_WRAPPER = 0x0257Ba4876863143bbeDB7847beC583e4deb6fE6;

1) why the address of maker, UNISWAP_FACTORY_A and UNISWAP_FACTORY_B are different?
2) In this contract should I add the UNISWAP_FACTORY_C, D, E and F that you create in the contract of my flash loan?

**Comment by amadeobrands** [comment]
It seems this works now and is not an issue any more any discussions please move to the forum thank you all :) Keep on building.
